### ISSUE TITLE
Doesn't work in IE 11

### ISSUE THREAD

**Issue by nashwaan** [nathanchase/super-minimal-aurelia#2] opened 2017-03-12 09:02 UTC
Hi Nathan,

Thanks for this great work to simplify Aurelia + Webpack + ES6 setup.

I tested this and it works on Chrome, Edge, Firefox. But not IE11.

The error in the console says `SCRIPT1014: Invalid character`.
It doesn't recognize ES6 string template, the ` character.
Is it because not transpiling from ES6 to ES5?

**Comment by nashwaan** [comment] 2017-03-13 03:54
I managed to get it working for IE11 by installing two packages:

`npm install --save-dev babel-preset-env es6-promise-promise`

Also, I made four changes to `webpack.config.js` file. See my inline comments marked as `(1)`, `(2)`, `(3)`, and `(4)`:

```js
const path = require("path");
const { AureliaPlugin } = require("aurelia-webpack-plugin");
const BabiliPlugin = require("babili-webpack-plugin");
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack'); // (1) to use webpack.ProvidePlugin()

module.exports = {
  entry: "aurelia-bootstrapper",

  output: {
    path: path.resolve(__dirname, "dist"),
    publicPath: "/",
    filename: "[name].js",    
    chunkFilename: "[name].js"
  },

  resolve: {
    extensions: [".js"],
    modules: ["src", "node_modules"].map(x => path.resolve(x)),
  },

  module: {
    rules: [
      {
        test: /\.(js)$/,
        loaders: 'babel-loader',
        exclude: /node_modules/,
        query: {
          presets: ['env'], // (2) to transpile to ES5
          plugins: ['transform-decorators-legacy' ]
        }
      },
      { test: /\.css$/i, 
        use: [
          "style-loader", 
          "css-loader"
        ] 
      },
      { test: /\.html$/i, 
        use: "html-loader" }
    ]
  },  

  plugins: [
    new webpack.ProvidePlugin({
      Promise: 'es6-promise-promise', // (3) to polyfill Promise object 
    }),
    new AureliaPlugin({
      // dist: 'es2015' // (4) don't transpile to es2015 (ES6) code
    }),
    new BabiliPlugin(),
    new HtmlWebpackPlugin({
      template: '!html-webpack-plugin/lib/loader!index.html',
      filename: 'index.html'
    }), 
  ],
};
```

**Comment by nathanchase** [comment] 2017-03-13 03:59
Ah, yes. I hadn't added the Promises polyfill in there, since this was a barebones concept. I use [Bluebird](https://github.com/petkaantonov/bluebird) for my Promises polyfill, but es6-promise-promise works too.

FYI, if you want to use fetch, you'll need a polyfill for that as well.

I use '[isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch)'.

You'd add that right alongside the Promise in the ProvidePlugin settings, like so:

```
 new ProvidePlugin({
        Promise: 'es6-promise-promise',
        fetch: 'isomorphic-fetch'
    }),
```

**Comment by nashwaan** [comment] 2017-03-13 04:34
Thanks for the tips.

Now it doesn't work for IE 10 `SCRIPT5009: 'Map' is undefined`. I don't know how to polyfill Map object correctly. I tried installing `npm install es6-map` and added this line:
```js
    new webpack.ProvidePlugin({
      Promise: 'es6-promise-promise',
      Map: 'es6-map'
    }),
```
But it doesn't work! Any idea how to polyfill Map object and get it working for IE10?

**Comment by nathanchase** [comment] 2017-03-13 04:48
I think it might be just including [aurelia-polyfills](https://github.com/aurelia/polyfills). Try just adding 'aurelia-polyfills' to your dependencies and see if that solves it.

`npm install --save aurelia-polyfills`

**Comment by nathanchase** [comment] 2017-03-13 04:50
https://github.com/paulmillr/es6-shim might be an option if aurelia-polyfills doesn't solve it.

**Comment by nashwaan** [comment] 2017-03-13 05:38
@nathanchase Thanks for your suggestions.

I am unable to get 'aurelia-polyfills' working in webpack.
I used the following in webpack:
```js
entry: ['babel-polyfill', 'aurelia-bootstrapper'],
```

I also tried `es6-shim` and used the following in webpack:
```js
entry: ['es6-shim', 'aurelia-bootstrapper'],
```

And also `babel-polyfill` :
```js
entry: ['babel-polyfill', 'aurelia-bootstrapper'],
```

None of them worked and I still get same error `SCRIPT5009: 'Map' is undefined` under IE10. 

Am I not configuring it in the right way in webpack? Do I need to add the polyfill to `ProvidePlugin()` as well?

(I know this issue is not directly related to your project, but I love like to get your minimal setup working for IE9 and upwards).

**Comment by nathanchase** [comment] 2017-03-15 23:45
On another app I'm working on, I use:
`entry: { main: [`aurelia-bootstrapper`,`babel-polyfill`]}`
but my app also errors in IE. It works fine in Edge.

If you find the solution, let me know - as I'd be interested to see what it takes to get old IE browsers to work too!

**Comment by nathanchase** [comment] 2017-03-15 23:52
Here are some places to start that might be of some help:
https://github.com/BryceHQ/es3ify-webpack-plugin
http://stackoverflow.com/questions/33512715/babel-6-0-20-modules-feature-not-work-in-ie8
https://github.com/jmcriffey/babel-preset-es2015-ie

My guess is it's something to do with the inherent Javascript rendering engine differences between Webkit browsers and older IE browsers.

**Comment by nashwaan** [comment] 2017-03-17 07:59
Since this repository is based on @jods4 work, I wish if he could shed some lights on this issue.

To @jods4: could you download this repo and make it work for IE10 & IE9, please?

**Comment by jods4** [comment] 2017-03-17 22:49
This repo doesn't seem meant for IE.
- Aurelia needs a `Promise` polyfill in IE. The simplest way is to take a dependency on `es6-promise-promise` and use Webpack `ProvidePlugin` as you commented above.
- You shouldn't use `dist: 'es2015'`, obviously. The default `native-modules` is your best choice on IE.
- The application javascript is ES6 with syntax like `=>`. You need to transpile that. Babel is in the config but only configured for decorators.

Those three changes should be enough to run in IE.

I am concerned by your error about `Map`. There is a basic polyfill for `Map` in `aurelia-polyfills`, which is automatically loaded during bootstrap. So it should not come as undefined... unless you have code that uses `Map` before Aurelia actually starts, of course.

**Comment by nashwaan** [comment] 2017-03-18 04:22
Thanks @jods4  for your comments.

I did the 3 suggestions that you mentioned and I managed to get it working for IE11. The issue we are facing now is for IE10 which is `SCRIPT5009: 'Map' is undefined`.

This repo is minimal and contains only basic Aurelia code. If Aurelia bootstrapper is already polyfilling Map object, then could it be `webpack` or your `aurelia-webpack-plugin` is needing Map object and IE10 is lacking it?

Also, what is the correct way to polyfill Map object via webpack? Any sample code?

**Comment by nathanchase** [comment] 2017-03-18 05:57
You should just be able to install [es6-map](https://github.com/medikoo/es6-map) and do this in your main.js:
`import Map from 'es6-map'`

**Comment by nathanchase** [comment] 2017-03-18 06:05
I tried the above and it still gave me an issue in IE10, but if I add it to the ProvidePlugin, I got this error instead:
` Object doesn't support this action`

from this code: 
```
module.exports = (function () {
	if (typeof Map === 'undefined') return false;
	return (Object.prototype.toString.call(new Map()) === '[object Map]');  // <-- this line was called out
}());
```

**Comment by jods4** [comment] 2017-03-18 16:27
I found out what happens here. It's a bug but I'm not sure what the proper fix is.
Webpack plugins load `aurelia-loader-webpack` very early, before `aurelia-polyfills` run.
`loader-webpack` imports `aurelia-metadata`, which instantiates a `Map`.

**Comment by nathanchase** [comment] 2017-03-18 16:51
Maybe have a Promise inside aurelia-loader-webpack that wait for external polyfills to load first, if they exist?

**Comment by jods4** [comment] 2017-03-18 17:10
`v2.0-rc2` branch has a fix for this. It runs in IE 10.

As for IE 9 there's yet another bug. I was unaware of it but since Dec. 2015 Aurelia needs `requestAnimationFrame` API without providing a polyfill itself. So either you add your own polyfill or it doesn't work in IE 9. I'm discussing with team if this is the intended behavior.

**Comment by jods4** [comment] 2017-03-18 17:16
Turns out Aurelia [needs more polyfills in older browsers](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/3).

So the official list of required polyfills that are not included in `aurelia-polyfills` is `Promise`, `requestAnimationFrame` and `MutationObserver`.

Those are available in all modern browsers, but as far as IE is concerned your needs are:
- `Promise`: IE 9-11
- `MutationObserver`: IE 9-10
- `requestAnimationFrame`: IE 9

**Comment by nashwaan** [comment] 2017-03-19 15:59
@jods4 how did you exactly managed to get it working for IE10?

I have this line in `devDependencies`:
```js
  "devDependencies": {
    "aurelia-webpack-plugin": "git://github.com/aurelia/webpack-plugin.git#v2.0-rc2",
```
and installed `es6-map` and added this line in `webpack.config.js`:
```js
        new webpack.ProvidePlugin({
            Map: 'es6-map',
            Promise: 'es6-promise-promise',
        }),
```
And i got this error under IE 11 & IE 10:
`SCRIPT445: Object doesn't support this action`

So what am I missing to get Map object work correctly under IE 10?

**Comment by jods4** [comment] 2017-03-19 17:09
@nashwaan Note that the RC2 branch does not include a built `dist` folder, so I think you're actually still using RC1 code!

You don't need `es6-map` (unless you really want to) as `aurelia-polyfills` includes it. The RC2 code ensures it's loaded early enough.

For IE 10 you'd most likely still need a `MutationObserver` polyfill, though.

**Comment by nathanchase** [comment] 2017-03-19 20:54
I tried [webcomponents.js-v1/dist/webcomponents](https://www.npmjs.com/package/webcomponents.js-v1) and [raf/polyfill](https://www.npmjs.com/package/raf), and it does get at least this repo to build and run in IE 11, but I still get `Map is undefined` in IE 10. Not sure what the workaround is yet.

**Comment by nathanchase** [comment] 2017-03-20 01:53
I've solved this! It's now working in IE 11, 10, and 9!

**Closed as completed by nathanchase** 2017-03-20 01:53 UTC

**Comment by nashwaan** [comment] 2017-03-20 04:46
Yes it works in IE11, IE10, and IE9.
Thanks @nathanchase and @jods4 .
